#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x597240FE94E60165 (rbtcollins@hp.com)
#
Name     : python-subunit
Version  : 1.2.0
Release  : 21
URL      : https://pypi.python.org/packages/source/p/python-subunit/python-subunit-1.2.0.tar.gz
Source0  : https://pypi.python.org/packages/source/p/python-subunit/python-subunit-1.2.0.tar.gz
Source99 : https://pypi.python.org/packages/source/p/python-subunit/python-subunit-1.2.0.tar.gz.asc
Summary  : Python implementation of subunit test streaming protocol
Group    : Development/Tools
License  : Apache-2.0
Requires: python-subunit-bin
Requires: python-subunit-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
subunit: A streaming protocol for test results
Licensed under either the Apache License, Version 2.0 or the BSD 3-clause
license at the users choice. A copy of both licenses are available in the
project source as Apache-2.0 and BSD. You may not use this file except in
compliance with one of these two licences.

%package bin
Summary: bin components for the python-subunit package.
Group: Binaries

%description bin
bin components for the python-subunit package.


%package python
Summary: python components for the python-subunit package.
Group: Default

%description python
python components for the python-subunit package.


%prep
%setup -q -n python-subunit-1.2.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484569428
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484569428
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/subunit-1to2
/usr/bin/subunit-2to1
/usr/bin/subunit-filter
/usr/bin/subunit-ls
/usr/bin/subunit-notify
/usr/bin/subunit-output
/usr/bin/subunit-stats
/usr/bin/subunit-tags
/usr/bin/subunit2csv
/usr/bin/subunit2gtk
/usr/bin/subunit2junitxml
/usr/bin/subunit2pyunit
/usr/bin/tap2subunit

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
